name: Build and Push Docker Images on Tagging

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Web Server Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./web
        file: ./web/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: danswer/danswer-web-server:${{ github.ref_name }}

    - name: Api Server Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./backend/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: danswer/danswer-backend:${{ github.ref_name }}
