name: Tag Latest Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version (ie v0.0.1) to tag as latest'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Enable Docker CLI experimental features
      run: echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $GITHUB_ENV

    - name: Pull, Tag and Push Web Server Image
      run: |
        docker pull danswer/danswer-web-server:${{ github.event.inputs.version }}
        docker tag danswer/danswer-web-server:${{ github.event.inputs.version }} danswer/danswer-web-server:latest
        docker push danswer/danswer-web-server:latest
        docker manifest create danswer/danswer-web-server:latest danswer/danswer-web-server:latest
        docker manifest push danswer/danswer-web-server:latest

    - name: Pull, Tag and Push API Server Image
      run: |
        docker pull danswer/danswer-api-server:${{ github.event.inputs.version }}
        docker tag danswer/danswer-api-server:${{ github.event.inputs.version }} danswer/danswer-api-server:latest
        docker push danswer/danswer-api-server:latest
        docker manifest create danswer/danswer-api-server:latest danswer/danswer-api-server:latest
        docker manifest push danswer/danswer-api-server:latest

    - name: Pull, Tag and Push Background Job Image
      run: |
        docker pull danswer/danswer-background:${{ github.event.inputs.version }}
        docker tag danswer/danswer-background:${{ github.event.inputs.version }} danswer/danswer-background:latest
        docker push danswer/danswer-background:latest
        docker manifest create danswer/danswer-background:latest danswer/danswer-background:latest
        docker manifest push danswer/danswer-background:latest
