name: Build and Push Web Image on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Web Image Docker Build and Push
      uses: docker/build-push-action@v5
      with:
        context: ./web
        file: ./web/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          danswer/danswer-web-server:${{ github.ref_name }}
          danswer/danswer-web-server:latest
        build-args: |
          DANSWER_VERSION=${{ github.ref_name }}
        # needed due to weird interactions with the builds for different platforms  
        no-cache: true

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: docker.io/danswer/danswer-web-server:${{ github.ref_name }}
        severity: 'CRITICAL,HIGH'
